
// This file was autogenerated by PeakRDL-uvm
package watchdog_ral;
    `include "uvm_macros.svh"
    import uvm_pkg::*;
    
    // reg - register_map::WDOGLOAD
    class register_map__WDOGLOAD extends uvm_reg;
        rand uvm_reg_field WDOGLOAD;

        function new(string name = "register_map__WDOGLOAD");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.WDOGLOAD = new("WDOGLOAD");
            this.WDOGLOAD.configure(this, 32, 0, "RW", 0, 'hffffffff, 1, 1, 0);
        endfunction : build
    endclass : register_map__WDOGLOAD

    // reg - register_map::WDOGVALUE
    class register_map__WDOGVALUE extends uvm_reg;
        rand uvm_reg_field WDOGVALUE;

        function new(string name = "register_map__WDOGVALUE");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.WDOGVALUE = new("WDOGVALUE");
            this.WDOGVALUE.configure(this, 32, 0, "RO", 1, 'hffffffff, 1, 1, 0);
        endfunction : build
    endclass : register_map__WDOGVALUE

    // reg - register_map::WDOGCONTROL
    class register_map__WDOGCONTROL extends uvm_reg;
        rand uvm_reg_field INTEN;
        rand uvm_reg_field RESEN;
        rand uvm_reg_field RESERVED_31_2;

        function new(string name = "register_map__WDOGCONTROL");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.INTEN = new("INTEN");
            this.INTEN.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.RESEN = new("RESEN");
            this.RESEN.configure(this, 1, 1, "RW", 0, 'h0, 1, 1, 0);
            this.RESERVED_31_2 = new("RESERVED_31_2");
            this.RESERVED_31_2.configure(this, 30, 2, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : register_map__WDOGCONTROL

    // reg - register_map::WDOGINTCLR
    class register_map__WDOGINTCLR extends uvm_reg;
        rand uvm_reg_field INTCLR;

        function new(string name = "register_map__WDOGINTCLR");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.INTCLR = new("INTCLR");
            this.INTCLR.configure(this, 32, 0, "WO", 0, 'h0, 0, 1, 0);
        endfunction : build
    endclass : register_map__WDOGINTCLR

    // reg - register_map::WDOGRIS
    class register_map__WDOGRIS extends uvm_reg;
        rand uvm_reg_field RAW_WATCHDOG_INTERRUPT;
        rand uvm_reg_field RESERVED_31_1;

        function new(string name = "register_map__WDOGRIS");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.RAW_WATCHDOG_INTERRUPT = new("RAW_WATCHDOG_INTERRUPT");
            this.RAW_WATCHDOG_INTERRUPT.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            this.RESERVED_31_1 = new("RESERVED_31_1");
            this.RESERVED_31_1.configure(this, 31, 1, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : register_map__WDOGRIS

    // reg - register_map::WDOGMIS
    class register_map__WDOGMIS extends uvm_reg;
        rand uvm_reg_field WATCHDOG_INTERRUPT;
        rand uvm_reg_field RESERVED_31_1;

        function new(string name = "register_map__WDOGMIS");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.WATCHDOG_INTERRUPT = new("WATCHDOG_INTERRUPT");
            this.WATCHDOG_INTERRUPT.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            this.RESERVED_31_1 = new("RESERVED_31_1");
            this.RESERVED_31_1.configure(this, 31, 1, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : register_map__WDOGMIS

    // reg - register_map::WDOGLOCK
    class register_map__WDOGLOCK extends uvm_reg;
        rand uvm_reg_field REGISTER_WRITE_ENABLE_STATUS;
        rand uvm_reg_field ENABLE_REGISTER_WRITES;

        function new(string name = "register_map__WDOGLOCK");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.REGISTER_WRITE_ENABLE_STATUS = new("REGISTER_WRITE_ENABLE_STATUS");
            this.REGISTER_WRITE_ENABLE_STATUS.configure(this, 1, 0, "RO", 1, 'h0, 1, 1, 0);
            this.ENABLE_REGISTER_WRITES = new("ENABLE_REGISTER_WRITES");
            this.ENABLE_REGISTER_WRITES.configure(this, 31, 1, "WO", 0, 'h0, 0, 1, 0);
        endfunction : build
    endclass : register_map__WDOGLOCK

    // reg - register_map::WDOGITCR
    class register_map__WDOGITCR extends uvm_reg;
        rand uvm_reg_field INTEGRATION_TEST_MODE_ENABLE;
        rand uvm_reg_field RESERVED_31_1;

        function new(string name = "register_map__WDOGITCR");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.INTEGRATION_TEST_MODE_ENABLE = new("INTEGRATION_TEST_MODE_ENABLE");
            this.INTEGRATION_TEST_MODE_ENABLE.configure(this, 1, 0, "RW", 0, 'h0, 1, 1, 0);
            this.RESERVED_31_1 = new("RESERVED_31_1");
            this.RESERVED_31_1.configure(this, 31, 1, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : register_map__WDOGITCR

    // reg - register_map::WDOGITOP
    class register_map__WDOGITOP extends uvm_reg;
        rand uvm_reg_field INTEGRATION_TEST_WDOGRES_VALUE;
        rand uvm_reg_field INTEGRATION_TEST_WDOGINT_VALUE;
        rand uvm_reg_field RESERVED_31_2;

        function new(string name = "register_map__WDOGITOP");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.INTEGRATION_TEST_WDOGRES_VALUE = new("INTEGRATION_TEST_WDOGRES_VALUE");
            this.INTEGRATION_TEST_WDOGRES_VALUE.configure(this, 1, 0, "WO", 0, 'h0, 1, 1, 0);
            this.INTEGRATION_TEST_WDOGINT_VALUE = new("INTEGRATION_TEST_WDOGINT_VALUE");
            this.INTEGRATION_TEST_WDOGINT_VALUE.configure(this, 1, 1, "WO", 0, 'h0, 1, 1, 0);
            this.RESERVED_31_2 = new("RESERVED_31_2");
            this.RESERVED_31_2.configure(this, 30, 2, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : register_map__WDOGITOP

    // reg - register_map::WDOGPERIPHID4
    class register_map__WDOGPERIPHID4 extends uvm_reg;
        rand uvm_reg_field JEP106_C_CODE;
        rand uvm_reg_field BLOCK_COUNT;
        rand uvm_reg_field RESERVED_31_8;

        function new(string name = "register_map__WDOGPERIPHID4");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.JEP106_C_CODE = new("JEP106_C_CODE");
            this.JEP106_C_CODE.configure(this, 4, 0, "RO", 0, 'h4, 1, 1, 0);
            this.BLOCK_COUNT = new("BLOCK_COUNT");
            this.BLOCK_COUNT.configure(this, 4, 4, "RO", 0, 'h0, 1, 1, 0);
            this.RESERVED_31_8 = new("RESERVED_31_8");
            this.RESERVED_31_8.configure(this, 24, 8, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : register_map__WDOGPERIPHID4

    // reg - register_map::WDOGPERIPHID5a
    class register_map__WDOGPERIPHID5a extends uvm_reg;
        rand uvm_reg_field PERIPHID5;
        rand uvm_reg_field RESERVED_31_8;

        function new(string name = "register_map__WDOGPERIPHID5a");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.PERIPHID5 = new("PERIPHID5");
            this.PERIPHID5.configure(this, 8, 0, "RO", 0, 'h0, 1, 1, 0);
            this.RESERVED_31_8 = new("RESERVED_31_8");
            this.RESERVED_31_8.configure(this, 24, 8, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : register_map__WDOGPERIPHID5a

    // reg - register_map::WDOGPERIPHID6a
    class register_map__WDOGPERIPHID6a extends uvm_reg;
        rand uvm_reg_field PERIPHID6;
        rand uvm_reg_field RESERVED_31_8;

        function new(string name = "register_map__WDOGPERIPHID6a");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.PERIPHID6 = new("PERIPHID6");
            this.PERIPHID6.configure(this, 8, 0, "RO", 0, 'h0, 1, 1, 0);
            this.RESERVED_31_8 = new("RESERVED_31_8");
            this.RESERVED_31_8.configure(this, 24, 8, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : register_map__WDOGPERIPHID6a

    // reg - register_map::WDOGPERIPHID7a
    class register_map__WDOGPERIPHID7a extends uvm_reg;
        rand uvm_reg_field PERIPHID7;
        rand uvm_reg_field RESERVED_31_8;

        function new(string name = "register_map__WDOGPERIPHID7a");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.PERIPHID7 = new("PERIPHID7");
            this.PERIPHID7.configure(this, 8, 0, "RO", 0, 'h0, 1, 1, 0);
            this.RESERVED_31_8 = new("RESERVED_31_8");
            this.RESERVED_31_8.configure(this, 24, 8, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : register_map__WDOGPERIPHID7a

    // reg - register_map::WDOGPERIPHID0
    class register_map__WDOGPERIPHID0 extends uvm_reg;
        rand uvm_reg_field PART_NUMBER_7_0;
        rand uvm_reg_field RESERVED_31_8;

        function new(string name = "register_map__WDOGPERIPHID0");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.PART_NUMBER_7_0 = new("PART_NUMBER_7_0");
            this.PART_NUMBER_7_0.configure(this, 8, 0, "RO", 0, 'h24, 1, 1, 0);
            this.RESERVED_31_8 = new("RESERVED_31_8");
            this.RESERVED_31_8.configure(this, 24, 8, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : register_map__WDOGPERIPHID0

    // reg - register_map::WDOGPERIPHID1
    class register_map__WDOGPERIPHID1 extends uvm_reg;
        rand uvm_reg_field PART_NUMBER_11_8;
        rand uvm_reg_field JEP106_ID_3_0;
        rand uvm_reg_field RESERVED_31_8;

        function new(string name = "register_map__WDOGPERIPHID1");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.PART_NUMBER_11_8 = new("PART_NUMBER_11_8");
            this.PART_NUMBER_11_8.configure(this, 4, 0, "RO", 0, 'h8, 1, 1, 0);
            this.JEP106_ID_3_0 = new("JEP106_ID_3_0");
            this.JEP106_ID_3_0.configure(this, 4, 4, "RO", 0, 'hb, 1, 1, 0);
            this.RESERVED_31_8 = new("RESERVED_31_8");
            this.RESERVED_31_8.configure(this, 24, 8, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : register_map__WDOGPERIPHID1

    // reg - register_map::WDOGPERIPHID2
    class register_map__WDOGPERIPHID2 extends uvm_reg;
        rand uvm_reg_field JEP106_ID_6_4;
        rand uvm_reg_field JEDEC_USED;
        rand uvm_reg_field REVISION;
        rand uvm_reg_field RESERVED_31_8;

        function new(string name = "register_map__WDOGPERIPHID2");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.JEP106_ID_6_4 = new("JEP106_ID_6_4");
            this.JEP106_ID_6_4.configure(this, 3, 0, "RO", 0, 'h3, 1, 1, 0);
            this.JEDEC_USED = new("JEDEC_USED");
            this.JEDEC_USED.configure(this, 1, 3, "RO", 0, 'h1, 1, 1, 0);
            this.REVISION = new("REVISION");
            this.REVISION.configure(this, 4, 4, "RO", 0, 'h1, 1, 1, 0);
            this.RESERVED_31_8 = new("RESERVED_31_8");
            this.RESERVED_31_8.configure(this, 24, 8, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : register_map__WDOGPERIPHID2

    // reg - register_map::WDOGPERIPHID3
    class register_map__WDOGPERIPHID3 extends uvm_reg;
        rand uvm_reg_field CUSTOMER_MODIFICATION;
        rand uvm_reg_field ECO_REVISION;
        rand uvm_reg_field RESERVED_31_8;

        function new(string name = "register_map__WDOGPERIPHID3");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.CUSTOMER_MODIFICATION = new("CUSTOMER_MODIFICATION");
            this.CUSTOMER_MODIFICATION.configure(this, 4, 0, "RO", 0, 'h0, 1, 1, 0);
            this.ECO_REVISION = new("ECO_REVISION");
            this.ECO_REVISION.configure(this, 4, 4, "RO", 0, 'h0, 1, 1, 0);
            this.RESERVED_31_8 = new("RESERVED_31_8");
            this.RESERVED_31_8.configure(this, 24, 8, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : register_map__WDOGPERIPHID3

    // reg - register_map::WDOGPCELLID0
    class register_map__WDOGPCELLID0 extends uvm_reg;
        rand uvm_reg_field COMPONENT_ID;
        rand uvm_reg_field RESERVED_31_8;

        function new(string name = "register_map__WDOGPCELLID0");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.COMPONENT_ID = new("COMPONENT_ID");
            this.COMPONENT_ID.configure(this, 8, 0, "RO", 0, 'hd, 1, 1, 0);
            this.RESERVED_31_8 = new("RESERVED_31_8");
            this.RESERVED_31_8.configure(this, 24, 8, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : register_map__WDOGPCELLID0

    // reg - register_map::WDOGPCELLID1
    class register_map__WDOGPCELLID1 extends uvm_reg;
        rand uvm_reg_field COMPONENT_ID;
        rand uvm_reg_field RESERVED_31_8;

        function new(string name = "register_map__WDOGPCELLID1");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.COMPONENT_ID = new("COMPONENT_ID");
            this.COMPONENT_ID.configure(this, 8, 0, "RO", 0, 'hf0, 1, 1, 0);
            this.RESERVED_31_8 = new("RESERVED_31_8");
            this.RESERVED_31_8.configure(this, 24, 8, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : register_map__WDOGPCELLID1

    // reg - register_map::WDOGPCELLID2
    class register_map__WDOGPCELLID2 extends uvm_reg;
        rand uvm_reg_field COMPONENT_ID;
        rand uvm_reg_field RESERVED_31_8;

        function new(string name = "register_map__WDOGPCELLID2");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.COMPONENT_ID = new("COMPONENT_ID");
            this.COMPONENT_ID.configure(this, 8, 0, "RO", 0, 'h5, 1, 1, 0);
            this.RESERVED_31_8 = new("RESERVED_31_8");
            this.RESERVED_31_8.configure(this, 24, 8, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : register_map__WDOGPCELLID2

    // reg - register_map::WDOGPCELLID3
    class register_map__WDOGPCELLID3 extends uvm_reg;
        rand uvm_reg_field COMPONENT_ID;
        rand uvm_reg_field RESERVED_31_8;

        function new(string name = "register_map__WDOGPCELLID3");
            super.new(name, 32, UVM_NO_COVERAGE);
        endfunction : new

        virtual function void build();
            this.COMPONENT_ID = new("COMPONENT_ID");
            this.COMPONENT_ID.configure(this, 8, 0, "RO", 0, 'hb1, 1, 1, 0);
            this.RESERVED_31_8 = new("RESERVED_31_8");
            this.RESERVED_31_8.configure(this, 24, 8, "RO", 0, 'h0, 1, 1, 0);
        endfunction : build
    endclass : register_map__WDOGPCELLID3

    // addrmap - register_map
    class register_map extends uvm_reg_block;
        rand register_map__WDOGLOAD WDOGLOAD;
        rand register_map__WDOGVALUE WDOGVALUE;
        rand register_map__WDOGCONTROL WDOGCONTROL;
        rand register_map__WDOGINTCLR WDOGINTCLR;
        rand register_map__WDOGRIS WDOGRIS;
        rand register_map__WDOGMIS WDOGMIS;
        rand register_map__WDOGLOCK WDOGLOCK;
        rand register_map__WDOGITCR WDOGITCR;
        rand register_map__WDOGITOP WDOGITOP;
        rand register_map__WDOGPERIPHID4 WDOGPERIPHID4;
        rand register_map__WDOGPERIPHID5a WDOGPERIPHID5a;
        rand register_map__WDOGPERIPHID6a WDOGPERIPHID6a;
        rand register_map__WDOGPERIPHID7a WDOGPERIPHID7a;
        rand register_map__WDOGPERIPHID0 WDOGPERIPHID0;
        rand register_map__WDOGPERIPHID1 WDOGPERIPHID1;
        rand register_map__WDOGPERIPHID2 WDOGPERIPHID2;
        rand register_map__WDOGPERIPHID3 WDOGPERIPHID3;
        rand register_map__WDOGPCELLID0 WDOGPCELLID0;
        rand register_map__WDOGPCELLID1 WDOGPCELLID1;
        rand register_map__WDOGPCELLID2 WDOGPCELLID2;
        rand register_map__WDOGPCELLID3 WDOGPCELLID3;

        function new(string name = "register_map");
            super.new(name);
        endfunction : new

        virtual function void build();
            this.default_map = create_map("reg_map", 0, 4, UVM_NO_ENDIAN);
            this.WDOGLOAD = new("WDOGLOAD");
            this.WDOGLOAD.configure(this);

            this.WDOGLOAD.build();
            this.default_map.add_reg(this.WDOGLOAD, 'h0);
            this.WDOGVALUE = new("WDOGVALUE");
            this.WDOGVALUE.configure(this);

            this.WDOGVALUE.build();
            this.default_map.add_reg(this.WDOGVALUE, 'h4);
            this.WDOGCONTROL = new("WDOGCONTROL");
            this.WDOGCONTROL.configure(this);

            this.WDOGCONTROL.build();
            this.default_map.add_reg(this.WDOGCONTROL, 'h8);
            this.WDOGINTCLR = new("WDOGINTCLR");
            this.WDOGINTCLR.configure(this);

            this.WDOGINTCLR.build();
            this.default_map.add_reg(this.WDOGINTCLR, 'hc);
            this.WDOGRIS = new("WDOGRIS");
            this.WDOGRIS.configure(this);

            this.WDOGRIS.build();
            this.default_map.add_reg(this.WDOGRIS, 'h10);
            this.WDOGMIS = new("WDOGMIS");
            this.WDOGMIS.configure(this);

            this.WDOGMIS.build();
            this.default_map.add_reg(this.WDOGMIS, 'h14);
            this.WDOGLOCK = new("WDOGLOCK");
            this.WDOGLOCK.configure(this);

            this.WDOGLOCK.build();
            this.default_map.add_reg(this.WDOGLOCK, 'hc00);
            this.WDOGITCR = new("WDOGITCR");
            this.WDOGITCR.configure(this);

            this.WDOGITCR.build();
            this.default_map.add_reg(this.WDOGITCR, 'hf00);
            this.WDOGITOP = new("WDOGITOP");
            this.WDOGITOP.configure(this);

            this.WDOGITOP.build();
            this.default_map.add_reg(this.WDOGITOP, 'hf04);
            this.WDOGPERIPHID4 = new("WDOGPERIPHID4");
            this.WDOGPERIPHID4.configure(this);

            this.WDOGPERIPHID4.build();
            this.default_map.add_reg(this.WDOGPERIPHID4, 'hfd0);
            this.WDOGPERIPHID5a = new("WDOGPERIPHID5a");
            this.WDOGPERIPHID5a.configure(this);

            this.WDOGPERIPHID5a.build();
            this.default_map.add_reg(this.WDOGPERIPHID5a, 'hfd4);
            this.WDOGPERIPHID6a = new("WDOGPERIPHID6a");
            this.WDOGPERIPHID6a.configure(this);

            this.WDOGPERIPHID6a.build();
            this.default_map.add_reg(this.WDOGPERIPHID6a, 'hfd8);
            this.WDOGPERIPHID7a = new("WDOGPERIPHID7a");
            this.WDOGPERIPHID7a.configure(this);

            this.WDOGPERIPHID7a.build();
            this.default_map.add_reg(this.WDOGPERIPHID7a, 'hfdc);
            this.WDOGPERIPHID0 = new("WDOGPERIPHID0");
            this.WDOGPERIPHID0.configure(this);

            this.WDOGPERIPHID0.build();
            this.default_map.add_reg(this.WDOGPERIPHID0, 'hfe0);
            this.WDOGPERIPHID1 = new("WDOGPERIPHID1");
            this.WDOGPERIPHID1.configure(this);

            this.WDOGPERIPHID1.build();
            this.default_map.add_reg(this.WDOGPERIPHID1, 'hfe4);
            this.WDOGPERIPHID2 = new("WDOGPERIPHID2");
            this.WDOGPERIPHID2.configure(this);

            this.WDOGPERIPHID2.build();
            this.default_map.add_reg(this.WDOGPERIPHID2, 'hfe8);
            this.WDOGPERIPHID3 = new("WDOGPERIPHID3");
            this.WDOGPERIPHID3.configure(this);

            this.WDOGPERIPHID3.build();
            this.default_map.add_reg(this.WDOGPERIPHID3, 'hfec);
            this.WDOGPCELLID0 = new("WDOGPCELLID0");
            this.WDOGPCELLID0.configure(this);

            this.WDOGPCELLID0.build();
            this.default_map.add_reg(this.WDOGPCELLID0, 'hff0);
            this.WDOGPCELLID1 = new("WDOGPCELLID1");
            this.WDOGPCELLID1.configure(this);

            this.WDOGPCELLID1.build();
            this.default_map.add_reg(this.WDOGPCELLID1, 'hff4);
            this.WDOGPCELLID2 = new("WDOGPCELLID2");
            this.WDOGPCELLID2.configure(this);

            this.WDOGPCELLID2.build();
            this.default_map.add_reg(this.WDOGPCELLID2, 'hff8);
            this.WDOGPCELLID3 = new("WDOGPCELLID3");
            this.WDOGPCELLID3.configure(this);

            this.WDOGPCELLID3.build();
            this.default_map.add_reg(this.WDOGPCELLID3, 'hffc);
        endfunction : build
    endclass : register_map

endpackage: watchdog_ral
