onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/write_enable00
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/PWDATA
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/reg_tx_buf
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/tx_buf_full
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/tx_buf_clear
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/tx_shift_buf
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/PCLK
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/nxt_tx_shift_buf
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/tx_buf_ctrl_shift
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/tx_buf_ctrl_load
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/TXD
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/update_reg_txd
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/uart_status
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/tx_tick_cnt
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/tx_state
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/tx_state_inc
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/BAUDTICK
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/tx_state_update
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/intr_state
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/intr_stat_set
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/intr_stat_clear
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/nxt_txd
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/nxt_tx_overrun
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/PENABLE
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/PCLKG
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/PADDR
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/PRDATA
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/PWRITE
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/PSLVERR
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/PSEL
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/PRESETn
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/PREADY
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/reg_ctrl
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/reg_txintr
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/reg_tx_overrun
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/UARTINT
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/TXOVRINT
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/TXINT
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/TXEN
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/tx_overrun
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/tx_overflow_intr
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/write_enable
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/write_enable04
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/write_enable08
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/write_enable0c
add wave -noupdate /tb_fpga_shield/u_fpga_top/u_fpga_system/u_user_partition/u_mps2_peripherals_wrapper/u_beetle_peripherals_fpga_subsystem/u_cmsdk_apb_uart_0/write_enable10
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {62498745 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {61698184 ps} {62694864 ps}
